### ISSUE TITLE
Video playback issue | MP4 vs MKV [solved]

### ISSUE THREAD

**Issue by xbmcnut** [rogro82/PiPup#19]
Hi there,

Thanks so much for making this! It is now my goto Home Assistant notification system.

I've used Postman to try sending video from my Home Assistant local file that creates a small MP4 when someone walks past my camera. PiPup does not like playing this file at all. Codec info below.
```
"@type": "Video",
"StreamOrder": "0",
"ID": "1",
"Format": "AVC",
"Format_Profile": "Main",
"Format_Level": "2.2",
"Format_Settings_CABAC": "Yes",
"Format_Settings_RefFrames": "1",
"CodecID": "avc1",
"Duration": "33.332",
"BitRate_Mode": "VBR",
"BitRate": "195528",
"BitRate_Maximum": "751616",
"Width": "640",
"Height": "360",
"Stored_Height": "368",
"Sampled_Width": "640",
"Sampled_Height": "360",
"PixelAspectRatio": "1.000",
"DisplayAspectRatio": "1.778",
"Rotation": "0.000",
"FrameRate_Mode": "VFR",
"FrameRate": "6.000",
"FrameRate_Minimum": "4.975",
"FrameRate_Maximum": "6.250",
"FrameCount": "200",
"ColorSpace": "YUV",
"ChromaSubsampling": "4:2:0",
"BitDepth": "8",
"ScanType": "Progressive",
"StreamSize": "814699",
"BufferSize": "4000000 / 4000000",
"colour_description_present": "Yes",
"colour_description_present_Source": "Stream",
"colour_range": "Full",
"colour_range_Source": "Stream",
"colour_primaries": "BT.709",
"colour_primaries_Source": "Stream",
"transfer_characteristics": "BT.709",
"transfer_characteristics_Source": "Stream",
"matrix_coefficients": "BT.709",
"matrix_coefficients_Source": "Stream",
"extra": {
"Codec_configuration_box": "avcC"
```
It does however play the Jellyfish Test Clip absolutely fine (codec info below). Unfortunately there is no way to manipulate the video being created by Home Assistant so I was hoping there is some tweak you can make to allow the MP4 to play properly?
```
"@type": "Video",
"StreamOrder": "0",
"ID": "1",
"UniqueID": "1970268483128847283",
"Format": "AVC",
"Format_Profile": "High",
"Format_Level": "4",
"Format_Settings_CABAC": "Yes",
"Format_Settings_RefFrames": "3",
"Format_Settings_GOP": "M=3, N=33",
"MuxingMode": "Header stripping",
"CodecID": "V_MPEG4/ISO/AVC",
"Duration": "59.977",
"BitRate": "2935108",
"Width": "1920",
"Height": "1080",
"Stored_Height": "1088",
"Sampled_Width": "1920",
"Sampled_Height": "1080",
"PixelAspectRatio": "1.000",
"DisplayAspectRatio": "1.778",
"FrameRate_Mode": "CFR",
"FrameRate": "23.976",
"FrameCount": "1438",
"Standard": "NTSC",
"ColorSpace": "YUV",
"ChromaSubsampling": "4:2:0",
"BitDepth": "8",
"ScanType": "Progressive",
"Delay": "0.000",
"StreamSize": "22004744",
"Language": "en",
"Default": "Yes",
"Forced": "No",
"colour_description_present": "Yes",
"colour_description_present_Source": "Stream",
"colour_range": "Limited",
"colour_range_Source": "Stream",
"colour_primaries": "BT.709",
"colour_primaries_Source": "Stream",
"transfer_characteristics": "BT.709",
"transfer_characteristics_Source": "Stream",
"matrix_coefficients": "BT.709",
"matrix_coefficients_Source": "Stream"
```

**Comment by hoasis2** [comment]
Can the default (system) WebView App play the video?

**Comment by xbmcnut** [comment]
Good tip! No. I've plugged it into the TV via a USB stick and it says the video is 7 seconds long and it plays super fast and is all over in about 3 seconds. The clip is actually 33 seconds long so it may be related to the keyframe/interframe interval? I'll try upping the frame rate as with the frame rate so low, it may only be seeing one keyframe?

**Comment by xbmcnut** [comment]
FYI, I've played around with the streams and tried two H.264 streams with varying keyframes. Reducing the keyframe down to 2 with a fps of 6 or down to 3 on a fps of 12 actually makes things worse! Android sees these clips as having 0 secs even though they are each 10s long. Work-in-progress.

**Comment by xbmcnut** [comment]
Found a workaround! The iFrame internal needs to be very high, longer than the clip length x fps. So if the fps is 12 and the clip length is 10s, the iFrame needs to be set to >120. Also worth noting is that HA records a variable bitrate stream regardless of the camera setting so you should be able to set the camera to VBR without issue. I'm using the 3rd stream on my HIK camera which is not used for anything else so all good.

![image](https://user-images.githubusercontent.com/1492137/79625069-78267180-817a-11ea-81fb-921e74d38c17.png)

**Comment by xbmcnut** [comment]
FYI, the below settings also work flawlessly and with a much smaller file size; 2.2Mb vs 16.2Mb.

![image](https://user-images.githubusercontent.com/1492137/79625325-7eb5e880-817c-11ea-81ca-cd1f73ea62b6.png)
