### ISSUE TITLE
invalid request: unkown uri: //

### ISSUE THREAD

**Issue by hungpr0** [rogro82/PiPup#4]
Hello,

Thanks for your work. Could you please help to check why I have this error?
curl --header "Content-Type: application/json" --request POST --data @text.json http://192.168.2.x:7979//notify
invalid request: unknown uri: //

That is response from the app.

cat text.json
{
  "duration": 30,
  "position": 0,
  "title": "Your awesome title",
  "titleColor": "#0066cc",
  "titleSize": 20,
  "message": "What ever you want to say... do it here...",
  "messageColor": "#000000",
  "messageSize": 14,
  "backgroundColor": "#ffffff",
  "media": { "image": {
    "uri": "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/cfcc3137009463.5731d08bd66a1.png", "width": 480
  }}
}

Thanks,
Hung

**Comment by rogro82** [comment]
I dont know if it is a typo but else it most likely is because of the double `/` in `http://192.168.2.x:7979//notify`

**Comment by hungpr0** [comment]
> 
> 
> I dont know if it is a typo but else it most likely is because of the double `/` in `http://192.168.2.x:7979//notify`
Thanks. It is because of double / :)
