### ISSUE TITLE
My photo is not showing

### ISSUE THREAD

**Issue by reyur** [rogro82/PiPup#59]
Hello.

I want to display a screenshot from my camera using a link like:
https://MYADDRESS.eu.jeedom.link/plugins/camera/core/php/snapshot.php?id=MYID&apikey=MYKEY
If I access this URL from my browser, I obtain an image in jpg format.
On the other hand, this is not displayed with PipUp.
JPG format not supported? Or problems because the format is not specified in the URL?

Thank you.

**Comment by wendy2702** [comment]
HTTPS might be the problem.

Can you try with http only!?

**Comment by reyur** [comment]
Maybe HTTPS, maybe authentication on jeedom.
I tried with 'autologin' (a jeedom plugin) : 
http://192.168.2.XX/plugins/autologin/core/php/go.php?apikey%BLABLABLA&id%BLABLA

--> With TV browser, I can access my photo.
--> With PIPup, same problem (no photo).

**Comment by wendy2702** [comment]
Are you able to get a simple text message displayed with Pipup?

**Comment by reyur** [comment]
Yes, the text displays perfectly. It's definitely a problem with the image.

**Comment by wendy2702** [comment]
Can you provide the image?

**Comment by reyur** [comment]
![snapshot](https://github.com/rogro82/PiPup/assets/11794987/8a0b1f32-1ccc-49f2-a93f-b078b21eea12)
Thank you for your help!

**Comment by reyur** [comment]
Hello. It's actually an authentication issue.
The url does not point directly to an image, but first does something to authenticate, so it doesn't work.
I get around the problem by displaying a web page, and not an image.
