### ISSUE TITLE
Philips Qv151e

### ISSUE THREAD

**Issue by RWissenburg** [rogro82/PiPup#6]
Not compatible with the philips Qv151e

![Knipsel4646](https://user-images.githubusercontent.com/32013370/66269654-2efc7900-e84b-11e9-887d-46bcd73ebc08.JPG)

Android version 5.1.1

**Comment by rogro82** [comment]
The minimum required version of Android TV is determined by the Play Store so if that states the device is incompatible it is either running an earlier version of Philips own converted Android OS or an old version of Android TV.
