### ISSUE TITLE
Audio muted on android TV after popup

### ISSUE THREAD

**Issue by MrS4u** [rogro82/PiPup#60]
As the title says, stream from camera works perfect, but the source becomes muted.
I have to change source on TV to get the sound from TV speakers again.

I am using muted video stream for camera video stream, and cannot fix the issue.

Anyone had same problem?

**Comment by blindguynar** [comment]
@MrS4u I recently started seeing this too.  Did you ever figure it out?

**Comment by blindguynar** [comment]
For anyone finding this issue i did find a simple and effective work around.  It's not great, but it works

By re-streaming the feed back through go2rtc and placing the media=video option i can strip the audio stream and the sound does NOT mute after video popup.  

Go2rtc.yaml config example (This is for a unifi camera and therefore port 7447 for the rtsp un-secure stream)
```
streams:
  doorbell_camera:
    - rtsp://192.168.xx.xxx:7447/MzKvSX6wVDaOgemh#media=video
```
    
Then the url for PiPup looks like this (webrtc used here, but you can have mse, hls, etc). Note this ip is the address of go2rtc server and NOT the camera.

`     url: http://192.168.xx.xxx:1984/stream.html?src=doorbell_camera&mode=webrtc`
     
Hope that makes sense.

**Comment by MrS4u** [comment]
> @MrS4u I recently started seeing this too. Did you ever figure it out?

Hi, yes, by creating some automation in HASS - that was changing the source back to original one, 3 seconds after activating the stream... The popup was still on, and the sound was back to source.

But now I have went over to TVoverlay app, and I like it much more.
https://github.com/gugutab/TvOverlay
