### ISSUE TITLE
Image tag

### ISSUE THREAD

**Issue by mvanhelmont** [rogro82/PiPup#7]
I dont get it to work to send a image tag from homey. I have installed foscam and hikvision. Pushing to mobile with a image tag works

**Comment by Rocodamelshe** [comment]
I added my Foscam as a virtual cam to Homey. Then u can use the tag from that cam to use in PiPup.
Just a small tip: With the Foscam ( when cam is capable ofcourse) i use the live stream to use in PiPup. Live stream is much cooler then a still image ofcourse. Like i said, your cam must be capable ofcourse.

**Comment by mvanhelmont** [comment]
I have a C1 how do you send the live feed

**Comment by Rocodamelshe** [comment]
C1 is not capable of sending a live feed. But can be added as a virtual cam to Homey to use the tags.

**Comment by Rocodamelshe** [comment]
![chrome_2019-11-07_17-49-53](https://user-images.githubusercontent.com/19249884/68409330-2ddea480-0187-11ea-83d1-51c3b6032260.png)

**Comment by mvanhelmont** [comment]
I will try it again but image was not send to it. What foscam do you have that support live feed?

**Comment by Rocodamelshe** [comment]
FI9828W

**Comment by Rocodamelshe** [comment]
But again: added as a virtual cam in Homey

**Comment by mvanhelmont** [comment]
O now i see what you mean. Not by installing the foscam app in homey. But use the experimental features inside homey i will give it a try thanks

**Comment by mvanhelmont** [comment]
It works so thanks
