### ISSUE TITLE
Please add support for RTSP

### ISSUE THREAD

**Issue by mvanhelmont** [rogro82/PiPup#8]
Hi Rogro,

i love the idea of the program and it is nice to have support for RTSP so we cam stream ip camera to it.

thanks

**Comment by hoasis2** [comment]
That would be excellent!

**Comment by hungpr0** [comment]
yes. That will be great!

**Comment by william-pyle** [comment]
would love that also!

**Comment by blademckain** [comment]
yeah! RTSP support will be great!

**Comment by madjam002** [comment]
My PR which enables Javascript in the WebView (https://github.com/rogro82/PiPup/pull/34) in conjunction with something like https://github.com/mpromonet/webrtc-streamer allows you to achieve nearly zero latency streaming of an RTSP stream.

Just set `media.web` instead of `media.video` and point it to the URL of your webrtc-streamer frontend.

Alternatively you could point the URL to a Home Assistant dashboard to show that instead.

**Comment by hungpr0** [comment]
> 
> 
> My PR which enables Javascript in the WebView (#34) in conjunction with something like https://github.com/mpromonet/webrtc-streamer allows you to achieve nearly zero latency streaming of an RTSP stream.
> 
> Just set `media.web` instead of `media.video` and point it to the URL of your webrtc-streamer frontend.
> 
> Alternatively you could point the URL to a Home Assistant dashboard to show that instead.

Hello madjam002,

Thanks for your comment. Is there any pre-built apk file that I can use to install?

**Comment by madjam002** [comment]
@Diamond2 Not at the moment, you'll need to clone and build it. I was hoping it would be merged soon but I'm not sure if this project is maintained anymore as there are a few PRs that are open.

**Comment by tungmeister** [comment]
@madjam002 any chance of an Apk to try out?
EDIT: compiled it myself - it's now working perfectly with my nest doorbell stream. Thanks.

**Comment by thelostandfoundgroup** [comment]
> @madjam002 any chance of an Apk to try out? EDIT: compiled it myself - it's now working perfectly with my nest doorbell stream. Thanks.

Can you share the APK please? Save me from having to build it :-)

**Comment by gmcmicken** [comment]
> @madjam002 any chance of an Apk to try out? EDIT: compiled it myself - it's now working perfectly with my nest doorbell stream. Thanks.

Hey @tungmeister can you help me out with the APK?

**Comment by gmcmicken** [comment]
APK available [here](https://github.com/gmcmicken/PiPup/releases/tag/web-javascript-1.0)

**Comment by jay448** [comment]
> APK available [here](https://github.com/gmcmicken/PiPup/releases/tag/web-javascript-1.0)

The APK you created works great! I'm now able to stream my WebRTC URL to my Android TV. I'm just having the issue of the live feed buffering like crazy during the showing of the video. Any idea how I could fix this? Does it have something to do with the WebRTC feed?

**Comment by gmcmicken** [comment]
> > APK available [here](https://github.com/gmcmicken/PiPup/releases/tag/web-javascript-1.0)
> 
> The APK you created works great! I'm now able to stream my WebRTC URL to my Android TV. I'm just having the issue of the live feed buffering like crazy during the showing of the video. Any idea how I could fix this? Does it have something to do with the WebRTC feed?

Ya, add "&webrtc=false" to the URL. I was having the same issue with buffering, and find that forcing mse mode worked better.

**Comment by jay448** [comment]
> > > APK available [here](https://github.com/gmcmicken/PiPup/releases/tag/web-javascript-1.0)
> > 
> > 
> > The APK you created works great! I'm now able to stream my WebRTC URL to my Android TV. I'm just having the issue of the live feed buffering like crazy during the showing of the video. Any idea how I could fix this? Does it have something to do with the WebRTC feed?
> 
> Ya, add "&webrtc=false" to the URL. I was having the same issue with buffering, and find that forcing mse mode worked better.

Thanks. Disabling this does appear to make thing a little better but this stream is still buffering. Can I find other URL agruments  somewhere to test around with? Perhaps there is a way to lower the stream quality? 

This is my current URL:
`https://*private*.duckdns.org:8123/webrtc/embed?url=voordeur1&webrtc=false`

**Comment by gmcmicken** [comment]
> > > > APK available [here](https://github.com/gmcmicken/PiPup/releases/tag/web-javascript-1.0)
> > > 
> > > 
> > > The APK you created works great! I'm now able to stream my WebRTC URL to my Android TV. I'm just having the issue of the live feed buffering like crazy during the showing of the video. Any idea how I could fix this? Does it have something to do with the WebRTC feed?
> > 
> > Ya, add "&webrtc=false" to the URL. I was having the same issue with buffering, and find that forcing mse mode worked better.
> 
> Thanks. Disabling this does appear to make thing a little better but this stream is still buffering. Can I find other URL agruments  somewhere to test around with? Perhaps there is a way to lower the stream quality? 
> 
> This is my current URL:
> `https://*private*.duckdns.org:8123/webrtc/embed?url=voordeur1&webrtc=false`

Maybe it was the other option mse=false, you can see all the params on the GitHub readme it's a direct copy of the card configuration parameters.

**Comment by Anon666333** [comment]
> Hi Rogro,
> 
> i love the idea of the program and it is nice to have support for RTSP so we cam stream ip camera to it.
> 
> thanks

@mvanhelmont 
I know this is an extremely old post and the issue has been resolved, but I believe you were trying to get this to work with a nest doorbell, yeah?
I saw somewhere that you compiled this yourself and got the nest doorbell live feed working with pipup... How? Any insight is greatly appreciated (sorry if I'm missing something already mentioned)

**Comment by chinswain** [comment]
Would also like to know how you got this working with a Nest doorbell.

**Comment by ZeroPing01** [comment]
Hi, 
By default it seems the audio is muted when playing the webrtc. 
Does anyone know if it is possible to unmute it ?

**Comment by Anon666333** [comment]
> Hi, By default it seems the audio is muted when playing the webrtc. Does anyone know if it is possible to unmute it ?

Try this? the "muted: false" variable in the webrtc.create_link may help.

```
alias: Display doorbell PIP Popup on TV
mode: single
variables:
  link_id: "{% for _ in range(40) %}{{ range(10)|random }}{% endfor %}"
sequence:
  - service: webrtc.create_link
    data:
      link_id: "{{ link_id }}"
      entity: camera.cameraname
      open_limit: 0
      time_to_live: 60
      muted: false
  - service: rest_command.pipup_url_on_tv
    data:
      title: Front
      position: 2
      width: 640
      url: https://publicHAAddress/webrtc/embed?url={{ link_id }}
```
